#!/bin/sh

PVER=${1:-41}
MAJ_MINOR=5.7
FULLVER=$MAJ_MINOR.$PVER
MIRROR=o.x320.net/u57  # no longer available on public mirrors
ORIGIN="http://$MIRROR/Downloads/MySQL-$MAJ_MINOR"
TARGZ="mysql-boost-$FULLVER.tar.gz"
GPG_SIGNATURE=${TARGZ}.asc

# TODO absolute directory from script dir?
TGTDIR=.
DST_TARGZ=mysql-${MAJ_MINOR}_${FULLVER}.orig.tar.gz
DST_ASC=$TGTDIR/${DST_TARGZ}.asc

gpg --import archive/mysql-build-pubkey-3A79BD29.asc || exit 1

CURL_PROGRESS_OPTION=--progress-bar # --no-progress-meter | --silent
# beware of Mirror sites returning HTML "Service temporarily unavailable" or 404
curl -o $TGTDIR/$TARGZ.md5 --remote-time $CURL_PROGRESS_OPTION $ORIGIN/$TARGZ.md5 || echo "$TARGZ.md5 not downloaded"
curl -o $TARGZ --remote-time $CURL_PROGRESS_OPTION $ORIGIN/$TARGZ || exit 1
ln -sf $TARGZ $DST_TARGZ
curl -o $DST_ASC --remote-time $CURL_PROGRESS_OPTION $ORIGIN/$GPG_SIGNATURE || exit 1

# last command $? is the script's $? anyway, but let's be explicit here
gpg --verify $DST_ASC 2> /dev/null || exit 1
